MUI_386_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\ccrootkit.obj \
    $(_OBJ_DIR)\i386\hideregkey.obj

MUI_IA64_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\ccrootkit.obj \
    $(_OBJ_DIR)\ia64\hideregkey.obj

MUI_AMD64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\ccrootkit.obj \
    $(_OBJ_DIR)\amd64\hideregkey.obj

MUI_ARM_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\ccrootkit.obj \
    $(_OBJ_DIR)\arm\hideregkey.obj

